/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
	scheme "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/clientset/versioned/scheme"
)

// ComputeDomainCliqueReservationsGetter has a method to return a ComputeDomainCliqueReservationInterface.
// A group's client should implement this interface.
type ComputeDomainCliqueReservationsGetter interface {
	ComputeDomainCliqueReservations() ComputeDomainCliqueReservationInterface
}

// ComputeDomainCliqueReservationInterface has methods to work with ComputeDomainCliqueReservation resources.
type ComputeDomainCliqueReservationInterface interface {
	Create(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.CreateOptions) (*v1beta1.ComputeDomainCliqueReservation, error)
	Update(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.UpdateOptions) (*v1beta1.ComputeDomainCliqueReservation, error)
	UpdateStatus(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.UpdateOptions) (*v1beta1.ComputeDomainCliqueReservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ComputeDomainCliqueReservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ComputeDomainCliqueReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueReservation, err error)
	ComputeDomainCliqueReservationExpansion
}

// computeDomainCliqueReservations implements ComputeDomainCliqueReservationInterface
type computeDomainCliqueReservations struct {
	client rest.Interface
}

// newComputeDomainCliqueReservations returns a ComputeDomainCliqueReservations
func newComputeDomainCliqueReservations(c *ResourceV1beta1Client) *computeDomainCliqueReservations {
	return &computeDomainCliqueReservations{
		client: c.RESTClient(),
	}
}

// Get takes name of the computeDomainCliqueReservation, and returns the corresponding computeDomainCliqueReservation object, and an error if there is any.
func (c *computeDomainCliqueReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainCliqueReservation, err error) {
	result = &v1beta1.ComputeDomainCliqueReservation{}
	err = c.client.Get().
		Resource("computedomaincliquereservations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ComputeDomainCliqueReservations that match those selectors.
func (c *computeDomainCliqueReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueReservationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ComputeDomainCliqueReservationList{}
	err = c.client.Get().
		Resource("computedomaincliquereservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested computeDomainCliqueReservations.
func (c *computeDomainCliqueReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("computedomaincliquereservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a computeDomainCliqueReservation and creates it.  Returns the server's representation of the computeDomainCliqueReservation, and an error, if there is any.
func (c *computeDomainCliqueReservations) Create(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.CreateOptions) (result *v1beta1.ComputeDomainCliqueReservation, err error) {
	result = &v1beta1.ComputeDomainCliqueReservation{}
	err = c.client.Post().
		Resource("computedomaincliquereservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueReservation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a computeDomainCliqueReservation and updates it. Returns the server's representation of the computeDomainCliqueReservation, and an error, if there is any.
func (c *computeDomainCliqueReservations) Update(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueReservation, err error) {
	result = &v1beta1.ComputeDomainCliqueReservation{}
	err = c.client.Put().
		Resource("computedomaincliquereservations").
		Name(computeDomainCliqueReservation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueReservation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *computeDomainCliqueReservations) UpdateStatus(ctx context.Context, computeDomainCliqueReservation *v1beta1.ComputeDomainCliqueReservation, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueReservation, err error) {
	result = &v1beta1.ComputeDomainCliqueReservation{}
	err = c.client.Put().
		Resource("computedomaincliquereservations").
		Name(computeDomainCliqueReservation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueReservation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the computeDomainCliqueReservation and deletes it. Returns an error if one occurs.
func (c *computeDomainCliqueReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("computedomaincliquereservations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *computeDomainCliqueReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("computedomaincliquereservations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched computeDomainCliqueReservation.
func (c *computeDomainCliqueReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueReservation, err error) {
	result = &v1beta1.ComputeDomainCliqueReservation{}
	err = c.client.Patch(pt).
		Resource("computedomaincliquereservations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
