/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
	scheme "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/clientset/versioned/scheme"
)

// ComputeDomainCliqueSnapshotsGetter has a method to return a ComputeDomainCliqueSnapshotInterface.
// A group's client should implement this interface.
type ComputeDomainCliqueSnapshotsGetter interface {
	ComputeDomainCliqueSnapshots(namespace string) ComputeDomainCliqueSnapshotInterface
}

// ComputeDomainCliqueSnapshotInterface has methods to work with ComputeDomainCliqueSnapshot resources.
type ComputeDomainCliqueSnapshotInterface interface {
	Create(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.CreateOptions) (*v1beta1.ComputeDomainCliqueSnapshot, error)
	Update(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (*v1beta1.ComputeDomainCliqueSnapshot, error)
	UpdateStatus(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (*v1beta1.ComputeDomainCliqueSnapshot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ComputeDomainCliqueSnapshot, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ComputeDomainCliqueSnapshotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueSnapshot, err error)
	ComputeDomainCliqueSnapshotExpansion
}

// computeDomainCliqueSnapshots implements ComputeDomainCliqueSnapshotInterface
type computeDomainCliqueSnapshots struct {
	client rest.Interface
	ns     string
}

// newComputeDomainCliqueSnapshots returns a ComputeDomainCliqueSnapshots
func newComputeDomainCliqueSnapshots(c *ResourceV1beta1Client, namespace string) *computeDomainCliqueSnapshots {
	return &computeDomainCliqueSnapshots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the computeDomainCliqueSnapshot, and returns the corresponding computeDomainCliqueSnapshot object, and an error if there is any.
func (c *computeDomainCliqueSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	result = &v1beta1.ComputeDomainCliqueSnapshot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ComputeDomainCliqueSnapshots that match those selectors.
func (c *computeDomainCliqueSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueSnapshotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ComputeDomainCliqueSnapshotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested computeDomainCliqueSnapshots.
func (c *computeDomainCliqueSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a computeDomainCliqueSnapshot and creates it.  Returns the server's representation of the computeDomainCliqueSnapshot, and an error, if there is any.
func (c *computeDomainCliqueSnapshots) Create(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.CreateOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	result = &v1beta1.ComputeDomainCliqueSnapshot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a computeDomainCliqueSnapshot and updates it. Returns the server's representation of the computeDomainCliqueSnapshot, and an error, if there is any.
func (c *computeDomainCliqueSnapshots) Update(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	result = &v1beta1.ComputeDomainCliqueSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		Name(computeDomainCliqueSnapshot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueSnapshot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *computeDomainCliqueSnapshots) UpdateStatus(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	result = &v1beta1.ComputeDomainCliqueSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		Name(computeDomainCliqueSnapshot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainCliqueSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the computeDomainCliqueSnapshot and deletes it. Returns an error if one occurs.
func (c *computeDomainCliqueSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *computeDomainCliqueSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched computeDomainCliqueSnapshot.
func (c *computeDomainCliqueSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	result = &v1beta1.ComputeDomainCliqueSnapshot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("computedomaincliquesnapshots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
