/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	resourcev1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
	versioned "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/clientset/versioned"
	internalinterfaces "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/informers/externalversions/internalinterfaces"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/pkg/nvidia.com/listers/resource/v1beta1"
)

// ComputeDomainCliqueRetirementEvidenceInformer provides access to a shared informer and lister for
// ComputeDomainCliqueRetirementEvidences.
type ComputeDomainCliqueRetirementEvidenceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ComputeDomainCliqueRetirementEvidenceLister
}

type computeDomainCliqueRetirementEvidenceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewComputeDomainCliqueRetirementEvidenceInformer constructs a new informer for ComputeDomainCliqueRetirementEvidence type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewComputeDomainCliqueRetirementEvidenceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredComputeDomainCliqueRetirementEvidenceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredComputeDomainCliqueRetirementEvidenceInformer constructs a new informer for ComputeDomainCliqueRetirementEvidence type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredComputeDomainCliqueRetirementEvidenceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1beta1().ComputeDomainCliqueRetirementEvidences(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1beta1().ComputeDomainCliqueRetirementEvidences(namespace).Watch(context.TODO(), options)
			},
		},
		&resourcev1beta1.ComputeDomainCliqueRetirementEvidence{},
		resyncPeriod,
		indexers,
	)
}

func (f *computeDomainCliqueRetirementEvidenceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredComputeDomainCliqueRetirementEvidenceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *computeDomainCliqueRetirementEvidenceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&resourcev1beta1.ComputeDomainCliqueRetirementEvidence{}, f.defaultInformer)
}

func (f *computeDomainCliqueRetirementEvidenceInformer) Lister() v1beta1.ComputeDomainCliqueRetirementEvidenceLister {
	return v1beta1.NewComputeDomainCliqueRetirementEvidenceLister(f.Informer().GetIndexer())
}
