/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// FakeComputeDomainCliqueSnapshots implements ComputeDomainCliqueSnapshotInterface
type FakeComputeDomainCliqueSnapshots struct {
	Fake *FakeResourceV1beta1
	ns   string
}

var computedomaincliquesnapshotsResource = v1beta1.SchemeGroupVersion.WithResource("computedomaincliquesnapshots")

var computedomaincliquesnapshotsKind = v1beta1.SchemeGroupVersion.WithKind("ComputeDomainCliqueSnapshot")

// Get takes name of the computeDomainCliqueSnapshot, and returns the corresponding computeDomainCliqueSnapshot object, and an error if there is any.
func (c *FakeComputeDomainCliqueSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(computedomaincliquesnapshotsResource, c.ns, name), &v1beta1.ComputeDomainCliqueSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), err
}

// List takes label and field selectors, and returns the list of ComputeDomainCliqueSnapshots that match those selectors.
func (c *FakeComputeDomainCliqueSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueSnapshotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(computedomaincliquesnapshotsResource, computedomaincliquesnapshotsKind, c.ns, opts), &v1beta1.ComputeDomainCliqueSnapshotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ComputeDomainCliqueSnapshotList{ListMeta: obj.(*v1beta1.ComputeDomainCliqueSnapshotList).ListMeta}
	for _, item := range obj.(*v1beta1.ComputeDomainCliqueSnapshotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeDomainCliqueSnapshots.
func (c *FakeComputeDomainCliqueSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(computedomaincliquesnapshotsResource, c.ns, opts))

}

// Create takes the representation of a computeDomainCliqueSnapshot and creates it.  Returns the server's representation of the computeDomainCliqueSnapshot, and an error, if there is any.
func (c *FakeComputeDomainCliqueSnapshots) Create(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.CreateOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(computedomaincliquesnapshotsResource, c.ns, computeDomainCliqueSnapshot), &v1beta1.ComputeDomainCliqueSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), err
}

// Update takes the representation of a computeDomainCliqueSnapshot and updates it. Returns the server's representation of the computeDomainCliqueSnapshot, and an error, if there is any.
func (c *FakeComputeDomainCliqueSnapshots) Update(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(computedomaincliquesnapshotsResource, c.ns, computeDomainCliqueSnapshot), &v1beta1.ComputeDomainCliqueSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeComputeDomainCliqueSnapshots) UpdateStatus(ctx context.Context, computeDomainCliqueSnapshot *v1beta1.ComputeDomainCliqueSnapshot, opts v1.UpdateOptions) (*v1beta1.ComputeDomainCliqueSnapshot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(computedomaincliquesnapshotsResource, "status", c.ns, computeDomainCliqueSnapshot), &v1beta1.ComputeDomainCliqueSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), err
}

// Delete takes name of the computeDomainCliqueSnapshot and deletes it. Returns an error if one occurs.
func (c *FakeComputeDomainCliqueSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(computedomaincliquesnapshotsResource, c.ns, name, opts), &v1beta1.ComputeDomainCliqueSnapshot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeDomainCliqueSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(computedomaincliquesnapshotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ComputeDomainCliqueSnapshotList{})
	return err
}

// Patch applies the patch and returns the patched computeDomainCliqueSnapshot.
func (c *FakeComputeDomainCliqueSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(computedomaincliquesnapshotsResource, c.ns, name, pt, data, subresources...), &v1beta1.ComputeDomainCliqueSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), err
}
