/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// FakeComputeDomainCliqueRetirementEvidences implements ComputeDomainCliqueRetirementEvidenceInterface
type FakeComputeDomainCliqueRetirementEvidences struct {
	Fake *FakeResourceV1beta1
	ns   string
}

var computedomaincliqueretirementevidencesResource = v1beta1.SchemeGroupVersion.WithResource("computedomaincliqueretirementevidences")

var computedomaincliqueretirementevidencesKind = v1beta1.SchemeGroupVersion.WithKind("ComputeDomainCliqueRetirementEvidence")

// Get takes name of the computeDomainCliqueRetirementEvidence, and returns the corresponding computeDomainCliqueRetirementEvidence object, and an error if there is any.
func (c *FakeComputeDomainCliqueRetirementEvidences) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(computedomaincliqueretirementevidencesResource, c.ns, name), &v1beta1.ComputeDomainCliqueRetirementEvidence{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueRetirementEvidence), err
}

// List takes label and field selectors, and returns the list of ComputeDomainCliqueRetirementEvidences that match those selectors.
func (c *FakeComputeDomainCliqueRetirementEvidences) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueRetirementEvidenceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(computedomaincliqueretirementevidencesResource, computedomaincliqueretirementevidencesKind, c.ns, opts), &v1beta1.ComputeDomainCliqueRetirementEvidenceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ComputeDomainCliqueRetirementEvidenceList{ListMeta: obj.(*v1beta1.ComputeDomainCliqueRetirementEvidenceList).ListMeta}
	for _, item := range obj.(*v1beta1.ComputeDomainCliqueRetirementEvidenceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeDomainCliqueRetirementEvidences.
func (c *FakeComputeDomainCliqueRetirementEvidences) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(computedomaincliqueretirementevidencesResource, c.ns, opts))

}

// Create takes the representation of a computeDomainCliqueRetirementEvidence and creates it.  Returns the server's representation of the computeDomainCliqueRetirementEvidence, and an error, if there is any.
func (c *FakeComputeDomainCliqueRetirementEvidences) Create(ctx context.Context, computeDomainCliqueRetirementEvidence *v1beta1.ComputeDomainCliqueRetirementEvidence, opts v1.CreateOptions) (result *v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(computedomaincliqueretirementevidencesResource, c.ns, computeDomainCliqueRetirementEvidence), &v1beta1.ComputeDomainCliqueRetirementEvidence{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueRetirementEvidence), err
}

// Update takes the representation of a computeDomainCliqueRetirementEvidence and updates it. Returns the server's representation of the computeDomainCliqueRetirementEvidence, and an error, if there is any.
func (c *FakeComputeDomainCliqueRetirementEvidences) Update(ctx context.Context, computeDomainCliqueRetirementEvidence *v1beta1.ComputeDomainCliqueRetirementEvidence, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(computedomaincliqueretirementevidencesResource, c.ns, computeDomainCliqueRetirementEvidence), &v1beta1.ComputeDomainCliqueRetirementEvidence{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueRetirementEvidence), err
}

// Delete takes name of the computeDomainCliqueRetirementEvidence and deletes it. Returns an error if one occurs.
func (c *FakeComputeDomainCliqueRetirementEvidences) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(computedomaincliqueretirementevidencesResource, c.ns, name, opts), &v1beta1.ComputeDomainCliqueRetirementEvidence{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeDomainCliqueRetirementEvidences) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(computedomaincliqueretirementevidencesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ComputeDomainCliqueRetirementEvidenceList{})
	return err
}

// Patch applies the patch and returns the patched computeDomainCliqueRetirementEvidence.
func (c *FakeComputeDomainCliqueRetirementEvidences) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(computedomaincliqueretirementevidencesResource, c.ns, name, pt, data, subresources...), &v1beta1.ComputeDomainCliqueRetirementEvidence{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainCliqueRetirementEvidence), err
}
