//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomain) DeepCopyInto(out *ComputeDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomain.
func (in *ComputeDomain) DeepCopy() *ComputeDomain {
	if in == nil {
		return nil
	}
	out := new(ComputeDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainChannelConfig) DeepCopyInto(out *ComputeDomainChannelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainChannelConfig.
func (in *ComputeDomainChannelConfig) DeepCopy() *ComputeDomainChannelConfig {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainChannelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainChannelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainChannelSpec) DeepCopyInto(out *ComputeDomainChannelSpec) {
	*out = *in
	out.ResourceClaimTemplate = in.ResourceClaimTemplate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainChannelSpec.
func (in *ComputeDomainChannelSpec) DeepCopy() *ComputeDomainChannelSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainClique) DeepCopyInto(out *ComputeDomainClique) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Daemons != nil {
		in, out := &in.Daemons, &out.Daemons
		*out = make([]*ComputeDomainDaemonInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ComputeDomainDaemonInfo)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainClique.
func (in *ComputeDomainClique) DeepCopy() *ComputeDomainClique {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainClique)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainClique) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueAssignment) DeepCopyInto(out *ComputeDomainCliqueAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueAssignment.
func (in *ComputeDomainCliqueAssignment) DeepCopy() *ComputeDomainCliqueAssignment {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueList) DeepCopyInto(out *ComputeDomainCliqueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomainClique, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueList.
func (in *ComputeDomainCliqueList) DeepCopy() *ComputeDomainCliqueList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueMember) DeepCopyInto(out *ComputeDomainCliqueMember) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueMember.
func (in *ComputeDomainCliqueMember) DeepCopy() *ComputeDomainCliqueMember {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueReservation) DeepCopyInto(out *ComputeDomainCliqueReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueReservation.
func (in *ComputeDomainCliqueReservation) DeepCopy() *ComputeDomainCliqueReservation {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueReservationList) DeepCopyInto(out *ComputeDomainCliqueReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomainCliqueReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueReservationList.
func (in *ComputeDomainCliqueReservationList) DeepCopy() *ComputeDomainCliqueReservationList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueReservationSpec) DeepCopyInto(out *ComputeDomainCliqueReservationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueReservationSpec.
func (in *ComputeDomainCliqueReservationSpec) DeepCopy() *ComputeDomainCliqueReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueReservationStatus) DeepCopyInto(out *ComputeDomainCliqueReservationStatus) {
	*out = *in
	if in.ReleasedAt != nil {
		in, out := &in.ReleasedAt, &out.ReleasedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueReservationStatus.
func (in *ComputeDomainCliqueReservationStatus) DeepCopy() *ComputeDomainCliqueReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueRetirementEvidence) DeepCopyInto(out *ComputeDomainCliqueRetirementEvidence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueRetirementEvidence.
func (in *ComputeDomainCliqueRetirementEvidence) DeepCopy() *ComputeDomainCliqueRetirementEvidence {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueRetirementEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueRetirementEvidence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueRetirementEvidenceList) DeepCopyInto(out *ComputeDomainCliqueRetirementEvidenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomainCliqueRetirementEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueRetirementEvidenceList.
func (in *ComputeDomainCliqueRetirementEvidenceList) DeepCopy() *ComputeDomainCliqueRetirementEvidenceList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueRetirementEvidenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueRetirementEvidenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueRetirementEvidenceSpec) DeepCopyInto(out *ComputeDomainCliqueRetirementEvidenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueRetirementEvidenceSpec.
func (in *ComputeDomainCliqueRetirementEvidenceSpec) DeepCopy() *ComputeDomainCliqueRetirementEvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueRetirementEvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueRetirementReceipt) DeepCopyInto(out *ComputeDomainCliqueRetirementReceipt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueRetirementReceipt.
func (in *ComputeDomainCliqueRetirementReceipt) DeepCopy() *ComputeDomainCliqueRetirementReceipt {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueRetirementReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueSnapshot) DeepCopyInto(out *ComputeDomainCliqueSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueSnapshot.
func (in *ComputeDomainCliqueSnapshot) DeepCopy() *ComputeDomainCliqueSnapshot {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueSnapshotList) DeepCopyInto(out *ComputeDomainCliqueSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomainCliqueSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueSnapshotList.
func (in *ComputeDomainCliqueSnapshotList) DeepCopy() *ComputeDomainCliqueSnapshotList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainCliqueSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueSnapshotReceipt) DeepCopyInto(out *ComputeDomainCliqueSnapshotReceipt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueSnapshotReceipt.
func (in *ComputeDomainCliqueSnapshotReceipt) DeepCopy() *ComputeDomainCliqueSnapshotReceipt {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueSnapshotReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueSnapshotSpec) DeepCopyInto(out *ComputeDomainCliqueSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueSnapshotSpec.
func (in *ComputeDomainCliqueSnapshotSpec) DeepCopy() *ComputeDomainCliqueSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainCliqueSnapshotStatus) DeepCopyInto(out *ComputeDomainCliqueSnapshotStatus) {
	*out = *in
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]ComputeDomainCliqueAssignment, len(*in))
		copy(*out, *in)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]ComputeDomainCliqueMember, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainCliqueSnapshotStatus.
func (in *ComputeDomainCliqueSnapshotStatus) DeepCopy() *ComputeDomainCliqueSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainCliqueSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainDaemonConfig) DeepCopyInto(out *ComputeDomainDaemonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainDaemonConfig.
func (in *ComputeDomainDaemonConfig) DeepCopy() *ComputeDomainDaemonConfig {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainDaemonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainDaemonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainDaemonInfo) DeepCopyInto(out *ComputeDomainDaemonInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainDaemonInfo.
func (in *ComputeDomainDaemonInfo) DeepCopy() *ComputeDomainDaemonInfo {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainDaemonInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainList) DeepCopyInto(out *ComputeDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainList.
func (in *ComputeDomainList) DeepCopy() *ComputeDomainList {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainNode) DeepCopyInto(out *ComputeDomainNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainNode.
func (in *ComputeDomainNode) DeepCopy() *ComputeDomainNode {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainResourceClaimTemplate) DeepCopyInto(out *ComputeDomainResourceClaimTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainResourceClaimTemplate.
func (in *ComputeDomainResourceClaimTemplate) DeepCopy() *ComputeDomainResourceClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainResourceClaimTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainSpec) DeepCopyInto(out *ComputeDomainSpec) {
	*out = *in
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(ComputeDomainChannelSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainSpec.
func (in *ComputeDomainSpec) DeepCopy() *ComputeDomainSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDomainStatus) DeepCopyInto(out *ComputeDomainStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]*ComputeDomainNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ComputeDomainNode)
				**out = **in
			}
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDomainStatus.
func (in *ComputeDomainStatus) DeepCopy() *ComputeDomainStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuConfig) DeepCopyInto(out *GpuConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(GpuSharing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuConfig.
func (in *GpuConfig) DeepCopy() *GpuConfig {
	if in == nil {
		return nil
	}
	out := new(GpuConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuSharing) DeepCopyInto(out *GpuSharing) {
	*out = *in
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MpsConfig != nil {
		in, out := &in.MpsConfig, &out.MpsConfig
		*out = new(MpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuSharing.
func (in *GpuSharing) DeepCopy() *GpuSharing {
	if in == nil {
		return nil
	}
	out := new(GpuSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOMMUConfig) DeepCopyInto(out *IOMMUConfig) {
	*out = *in
	if in.EnableAPIDevice != nil {
		in, out := &in.EnableAPIDevice, &out.EnableAPIDevice
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOMMUConfig.
func (in *IOMMUConfig) DeepCopy() *IOMMUConfig {
	if in == nil {
		return nil
	}
	out := new(IOMMUConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigDeviceConfig) DeepCopyInto(out *MigDeviceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(MigDeviceSharing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigDeviceConfig.
func (in *MigDeviceConfig) DeepCopy() *MigDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(MigDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigDeviceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigDeviceSharing) DeepCopyInto(out *MigDeviceSharing) {
	*out = *in
	if in.MpsConfig != nil {
		in, out := &in.MpsConfig, &out.MpsConfig
		*out = new(MpsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigDeviceSharing.
func (in *MigDeviceSharing) DeepCopy() *MigDeviceSharing {
	if in == nil {
		return nil
	}
	out := new(MigDeviceSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MpsConfig) DeepCopyInto(out *MpsConfig) {
	*out = *in
	if in.DefaultActiveThreadPercentage != nil {
		in, out := &in.DefaultActiveThreadPercentage, &out.DefaultActiveThreadPercentage
		*out = new(int)
		**out = **in
	}
	if in.DefaultPinnedDeviceMemoryLimit != nil {
		in, out := &in.DefaultPinnedDeviceMemoryLimit, &out.DefaultPinnedDeviceMemoryLimit
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DefaultPerDevicePinnedMemoryLimit != nil {
		in, out := &in.DefaultPerDevicePinnedMemoryLimit, &out.DefaultPerDevicePinnedMemoryLimit
		*out = make(MpsPerDevicePinnedMemoryLimit, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MultiUser != nil {
		in, out := &in.MultiUser, &out.MultiUser
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MpsConfig.
func (in *MpsConfig) DeepCopy() *MpsConfig {
	if in == nil {
		return nil
	}
	out := new(MpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MpsPerDevicePinnedMemoryLimit) DeepCopyInto(out *MpsPerDevicePinnedMemoryLimit) {
	{
		in := &in
		*out = make(MpsPerDevicePinnedMemoryLimit, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MpsPerDevicePinnedMemoryLimit.
func (in MpsPerDevicePinnedMemoryLimit) DeepCopy() MpsPerDevicePinnedMemoryLimit {
	if in == nil {
		return nil
	}
	out := new(MpsPerDevicePinnedMemoryLimit)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfig) DeepCopyInto(out *TimeSlicingConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(TimeSliceInterval)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfig.
func (in *TimeSlicingConfig) DeepCopy() *TimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VfioDeviceConfig) DeepCopyInto(out *VfioDeviceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Iommu != nil {
		in, out := &in.Iommu, &out.Iommu
		*out = new(IOMMUConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VfioDeviceConfig.
func (in *VfioDeviceConfig) DeepCopy() *VfioDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(VfioDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VfioDeviceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
