/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// ComputeDomainCliqueReservationLister helps list ComputeDomainCliqueReservations.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueReservationLister interface {
	// List lists all ComputeDomainCliqueReservations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueReservation, err error)
	// Get retrieves the ComputeDomainCliqueReservation from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ComputeDomainCliqueReservation, error)
	ComputeDomainCliqueReservationListerExpansion
}

// computeDomainCliqueReservationLister implements the ComputeDomainCliqueReservationLister interface.
type computeDomainCliqueReservationLister struct {
	indexer cache.Indexer
}

// NewComputeDomainCliqueReservationLister returns a new ComputeDomainCliqueReservationLister.
func NewComputeDomainCliqueReservationLister(indexer cache.Indexer) ComputeDomainCliqueReservationLister {
	return &computeDomainCliqueReservationLister{indexer: indexer}
}

// List lists all ComputeDomainCliqueReservations in the indexer.
func (s *computeDomainCliqueReservationLister) List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueReservation, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ComputeDomainCliqueReservation))
	})
	return ret, err
}

// Get retrieves the ComputeDomainCliqueReservation from the index for a given name.
func (s *computeDomainCliqueReservationLister) Get(name string) (*v1beta1.ComputeDomainCliqueReservation, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("computedomaincliquereservation"), name)
	}
	return obj.(*v1beta1.ComputeDomainCliqueReservation), nil
}
