/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// ComputeDomainCliqueSnapshotLister helps list ComputeDomainCliqueSnapshots.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueSnapshotLister interface {
	// List lists all ComputeDomainCliqueSnapshots in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueSnapshot, err error)
	// ComputeDomainCliqueSnapshots returns an object that can list and get ComputeDomainCliqueSnapshots.
	ComputeDomainCliqueSnapshots(namespace string) ComputeDomainCliqueSnapshotNamespaceLister
	ComputeDomainCliqueSnapshotListerExpansion
}

// computeDomainCliqueSnapshotLister implements the ComputeDomainCliqueSnapshotLister interface.
type computeDomainCliqueSnapshotLister struct {
	indexer cache.Indexer
}

// NewComputeDomainCliqueSnapshotLister returns a new ComputeDomainCliqueSnapshotLister.
func NewComputeDomainCliqueSnapshotLister(indexer cache.Indexer) ComputeDomainCliqueSnapshotLister {
	return &computeDomainCliqueSnapshotLister{indexer: indexer}
}

// List lists all ComputeDomainCliqueSnapshots in the indexer.
func (s *computeDomainCliqueSnapshotLister) List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueSnapshot, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ComputeDomainCliqueSnapshot))
	})
	return ret, err
}

// ComputeDomainCliqueSnapshots returns an object that can list and get ComputeDomainCliqueSnapshots.
func (s *computeDomainCliqueSnapshotLister) ComputeDomainCliqueSnapshots(namespace string) ComputeDomainCliqueSnapshotNamespaceLister {
	return computeDomainCliqueSnapshotNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ComputeDomainCliqueSnapshotNamespaceLister helps list and get ComputeDomainCliqueSnapshots.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueSnapshotNamespaceLister interface {
	// List lists all ComputeDomainCliqueSnapshots in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueSnapshot, err error)
	// Get retrieves the ComputeDomainCliqueSnapshot from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ComputeDomainCliqueSnapshot, error)
	ComputeDomainCliqueSnapshotNamespaceListerExpansion
}

// computeDomainCliqueSnapshotNamespaceLister implements the ComputeDomainCliqueSnapshotNamespaceLister
// interface.
type computeDomainCliqueSnapshotNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ComputeDomainCliqueSnapshots in the indexer for a given namespace.
func (s computeDomainCliqueSnapshotNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueSnapshot, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ComputeDomainCliqueSnapshot))
	})
	return ret, err
}

// Get retrieves the ComputeDomainCliqueSnapshot from the indexer for a given namespace and name.
func (s computeDomainCliqueSnapshotNamespaceLister) Get(name string) (*v1beta1.ComputeDomainCliqueSnapshot, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("computedomaincliquesnapshot"), name)
	}
	return obj.(*v1beta1.ComputeDomainCliqueSnapshot), nil
}
