/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// ComputeDomainCliqueRetirementEvidenceLister helps list ComputeDomainCliqueRetirementEvidences.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueRetirementEvidenceLister interface {
	// List lists all ComputeDomainCliqueRetirementEvidences in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueRetirementEvidence, err error)
	// ComputeDomainCliqueRetirementEvidences returns an object that can list and get ComputeDomainCliqueRetirementEvidences.
	ComputeDomainCliqueRetirementEvidences(namespace string) ComputeDomainCliqueRetirementEvidenceNamespaceLister
	ComputeDomainCliqueRetirementEvidenceListerExpansion
}

// computeDomainCliqueRetirementEvidenceLister implements the ComputeDomainCliqueRetirementEvidenceLister interface.
type computeDomainCliqueRetirementEvidenceLister struct {
	indexer cache.Indexer
}

// NewComputeDomainCliqueRetirementEvidenceLister returns a new ComputeDomainCliqueRetirementEvidenceLister.
func NewComputeDomainCliqueRetirementEvidenceLister(indexer cache.Indexer) ComputeDomainCliqueRetirementEvidenceLister {
	return &computeDomainCliqueRetirementEvidenceLister{indexer: indexer}
}

// List lists all ComputeDomainCliqueRetirementEvidences in the indexer.
func (s *computeDomainCliqueRetirementEvidenceLister) List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ComputeDomainCliqueRetirementEvidence))
	})
	return ret, err
}

// ComputeDomainCliqueRetirementEvidences returns an object that can list and get ComputeDomainCliqueRetirementEvidences.
func (s *computeDomainCliqueRetirementEvidenceLister) ComputeDomainCliqueRetirementEvidences(namespace string) ComputeDomainCliqueRetirementEvidenceNamespaceLister {
	return computeDomainCliqueRetirementEvidenceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ComputeDomainCliqueRetirementEvidenceNamespaceLister helps list and get ComputeDomainCliqueRetirementEvidences.
// All objects returned here must be treated as read-only.
type ComputeDomainCliqueRetirementEvidenceNamespaceLister interface {
	// List lists all ComputeDomainCliqueRetirementEvidences in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueRetirementEvidence, err error)
	// Get retrieves the ComputeDomainCliqueRetirementEvidence from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ComputeDomainCliqueRetirementEvidence, error)
	ComputeDomainCliqueRetirementEvidenceNamespaceListerExpansion
}

// computeDomainCliqueRetirementEvidenceNamespaceLister implements the ComputeDomainCliqueRetirementEvidenceNamespaceLister
// interface.
type computeDomainCliqueRetirementEvidenceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ComputeDomainCliqueRetirementEvidences in the indexer for a given namespace.
func (s computeDomainCliqueRetirementEvidenceNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.ComputeDomainCliqueRetirementEvidence, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ComputeDomainCliqueRetirementEvidence))
	})
	return ret, err
}

// Get retrieves the ComputeDomainCliqueRetirementEvidence from the indexer for a given namespace and name.
func (s computeDomainCliqueRetirementEvidenceNamespaceLister) Get(name string) (*v1beta1.ComputeDomainCliqueRetirementEvidence, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("computedomaincliqueretirementevidence"), name)
	}
	return obj.(*v1beta1.ComputeDomainCliqueRetirementEvidence), nil
}
